# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7272f740a6e150e642d7386c2ca4b6558c33d9ea4954110ac7212c45d3dcc00e59a487fa4b22cf632d63dd6e0d7341381cd5d5fdf2cf722f0f458571f43962e

test:
  secret_key_base: 3c2e9eeaeafeab86be5fdc95565f7ed82b6d57d48e7b22327034ca105e3a568e832a36c702fa23863df8b319b3c5a892f42a1ca0bcf931f6543930301e1f11ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
